name: 03 - Workflow Runners

on: workflow_dispatch

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show Operating System
              run: |
                echo "This job is running on an Ubuntu Runner."
                echo "Runner OS: $RUNNER_OS"
